### PR TITLE
[JENKINS-33105] preserve blank/empty lines

### PR DESCRIPTION
**Pull request by benjaminfuchs**
- [x] Automated tests (see https://github.com/jenkinsci/acceptance-test-harness/pull/350)

Hi, 
my first commit didnt really fix this problem in all situations. This one I tested with following script before/after:

```
echo ""
echo " "
echo "  "
echo """
"""
```

**BEFORE:** 
screenshot from 2017-07-26 01-13-48

**AFTER:**
screenshot from 2017-07-26 01-11-41

I dont know right now how to test this, if you have an idea I would try to implement the test.
Greetings, Ben

### CODE REVIEW

**Comment by arthurzenika** [comment]
Am interrested in this fix. Any chance to see a release of the plugin so it's installable ?

**Comment by arthurzenika** [comment]
@Vlatombe @benjaminfuchs any chance of seeing a release soon ? (sorry can't get an account on jenkins issue track to ping you there)

**Comment by benjaminfuchs** [comment]
@arthurlogilab Sure, I will try to contact @Vlatombe directly since I also need to get ride of my SNAPSHOT version in my jenkins instances.

**Comment by Vlatombe** [comment]
@arthurlogilab @benjaminfuchs just released 1.2, it should appear soon in the Update Center. Thanks for your PRs @benjaminfuchs !

**Comment by arthurzenika** [comment]
Thanks a bunch!

While I'm at it, do you know of a plugin that would split the log file according to a given pattern ? (We do a bunch of things in docker-compose and send out the logs to stdout which is useful, but it would be even more awesome to be able to read the logs for each individual docker instance )

**Pull request merged**
